#!/usr/bin/env python3
"""Generate local Python bindings from the ratified invocation schema IDs."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "unstructured_platform_plugins" / "generated"
API_ROOT = "repos/Unstructured-IO/schemas-experimental/contents"

CONTRACTS = {
    "invocation_context_v1.py": {
        "schema": f"{API_ROOT}/schemas/ratified-types/invocation-context/v1.json?ref=main",
        "typeviz": f"{API_ROOT}/web/public/typeviz/invocation-context-v1.json?ref=main",
        "schema_id": "https://schemas.u10d.dev/invocation-context/v1.json",
        "root_type": "InvocationContext",
    },
    "error_audience_v1.py": {
        "schema": f"{API_ROOT}/schemas/ratified-types/errors/audience/v1.json?ref=main",
        "typeviz": f"{API_ROOT}/web/public/typeviz/errors-audience-v1.json?ref=main",
        "schema_id": "https://schemas.u10d.dev/errors/audience/v1.json",
        "root_type": "ErrorAudience",
    },
}


def _load_json(api_path: str) -> dict[str, Any]:
    completed = subprocess.run(
        ["gh", "api", "-H", "Accept: application/vnd.github.raw+json", api_path],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(completed.stdout)


def _python_binding(sidecar: dict[str, Any]) -> str:
    for binding in sidecar["bindings"]:
        if binding["key"] == "python":
            return binding["code"].rstrip() + "\n"
    raise ValueError("typeviz sidecar has no Python binding")


def _render(spec: dict[str, str]) -> str:
    schema = _load_json(spec["schema"])
    sidecar = _load_json(spec["typeviz"])
    if schema["$id"] != spec["schema_id"]:
        raise ValueError(f"unexpected schema id: {schema['$id']}")
    if sidecar["root_type_name"] != spec["root_type"]:
        raise ValueError(f"unexpected root type: {sidecar['root_type_name']}")

    canonical = json.dumps(schema, sort_keys=True, separators=(",", ":")).encode()
    schema_hash = hashlib.sha256(canonical).hexdigest()
    generated = _python_binding(sidecar)
    if spec["root_type"] == "InvocationContext":
        generated = generated.replace(
            "from typing import Any, Literal", "from typing import Literal"
        )
    else:
        generated = generated.replace("\nfrom pydantic import BaseModel, Field\n", "")
    provenance = (
        "\n# Generation provenance used by drift tests and reviewers.\n"
        f"SCHEMA_ID = {schema['$id']!r}\n"
        f"SCHEMA_SHA256 = {schema_hash!r}\n"
    )
    if spec["root_type"] == "InvocationContext":
        policy = schema["x-unstructured-version-policy"]
        provenance += (
            f"RESERVED_CONTEXT_KEY = {schema['x-unstructured-reserved-key']!r}\n"
            f"SUPPORTED_CONTEXT_VERSIONS = frozenset({policy['supported']!r})\n"
            f"DIMENSION_FIELDS = {tuple(schema['x-unstructured-dimension-fields'])!r}\n"
        )
    return (
        "# Generated by scripts/generate_invocation_contracts.py; do not edit by hand.\n"
        "# ruff: noqa: E501\n"
        f"# Source: {spec['schema_id']}\n"
        + generated
        + provenance
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for filename, spec in CONTRACTS.items():
        output = OUTPUT_DIR / filename
        rendered = _render(spec)
        if args.check:
            if not output.exists() or output.read_text() != rendered:
                stale.append(str(output.relative_to(ROOT)))
        else:
            output.write_text(rendered)

    if stale:
        print("stale generated invocation contracts:", *stale, sep="\n  ", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
