#!/usr/bin/env bash

pushd ./requirements || exit

find . -type f -name "*.txt" ! -name "constraints.txt" -exec rm '{}' ';'
find . -type f -name "*.in" -maxdepth 1 -exec pip-compile --upgrade '{}' ';'

popd || exit

# Check python version
# python version must match lowest supported (3.10)
major=3
minor=10

versions=$(cat requirements/* | grep "This file is autogenerated by pip-compile with Python" | awk '{print $NF}' | sort | uniq)
if [[ $(echo $versions | wc -w) -ne 1 ]]; then
	echo "Files generated with multiple python version: $versions"
	exit 1
fi

version_major=$(echo $versions | awk -F"." '{print $1}')
version_minor=$(echo $versions | awk -F"." '{print $2}')

if [[ $major -ne $version_major || $minor -ne $version_minor ]]; then
	echo "python version not equal to expected $major.$minor: $versions"
	exit 1
fi
